/**
 * Agent Code Generator — Phase 40.
 * Generates a ready-to-run TypeScript agent file from an Agent Blueprint Package (ABP).
 *
 * Output: a single .ts file the developer can drop into their project,
 * implement the tool handlers, and run with ts-node or tsx.
 *
 * Uses buildAgentSystemPrompt from the test harness to build the system prompt
 * (same function that powers simulation and test execution).
 */

import type { ABP } from "@/lib/types/abp";
import { buildAgentSystemPrompt } from "@/lib/testing/executor";

export interface CodeExportMeta {
  blueprintId: string;
  agentId: string;
  version: string;
  exportedAt: string;
}

/**
 * Generates a TypeScript agent file from an ABP.
 * Returns the file content as a string.
 */
export function generateAgentCode(abp: ABP, meta: CodeExportMeta): string {
  const systemPrompt = buildAgentSystemPrompt(abp);
  const maxTokens = abp.constraints?.max_tokens_per_response ?? 1024;
  const safeName = abp.identity.name.replace(/[^a-zA-Z0-9_]/g, "_");
  const tools = abp.capabilities?.tools ?? [];

  // ── Tool definitions ───────────────────────────────────────────────────────
  const toolDefsCode = tools.length === 0
    ? "const tools: Anthropic.Tool[] = [];"
    : [
        "const tools: Anthropic.Tool[] = [",
        ...tools.map((tool, i) => {
          const isLast = i === tools.length - 1;
          return [
            "  {",
            `    name: ${JSON.stringify(tool.name)},`,
            `    description: ${JSON.stringify(tool.description ?? `${tool.type} tool`)},`,
            "    input_schema: {",
            "      type: \"object\" as const,",
            "      properties: {",
            "        input: { type: \"string\", description: \"Input to the tool\" },",
            "      },",
            "      required: [\"input\"],",
            "    },",
            `  }${isLast ? "" : ","}`,
          ].join("\n");
        }),
        "];",
      ].join("\n");

  // ── Tool handlers ──────────────────────────────────────────────────────────
  const toolHandlersCode = tools.length === 0
    ? "const toolHandlers: Record<string, (input: Record<string, unknown>) => Promise<string>> = {};"
    : [
        "const toolHandlers: Record<string, (input: Record<string, unknown>) => Promise<string>> = {",
        ...tools.map((tool, i) => {
          const isLast = i === tools.length - 1;
          const comment = `${tool.type}${tool.description ? ` — ${tool.description}` : ""}`;
          return [
            `  ${JSON.stringify(tool.name)}: async (_input) => {`,
            `    // TODO: implement ${tool.name} (${comment})`,
            `    throw new Error(${JSON.stringify(`${tool.name}: not implemented`)});`,
            `  }${isLast ? "" : ","}`,
          ].join("\n");
        }),
        "};",
      ].join("\n");

  // ── Escape backticks in system prompt for template literal ─────────────────
  const escapedSystemPrompt = systemPrompt
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");

  return `/**
 * ${abp.identity.name} — AI Agent
 * Generated by Intellios from Blueprint ${meta.blueprintId}
 * Agent ID: ${meta.agentId} · Version: ${meta.version}
 * Exported: ${meta.exportedAt}
 *
 * Quick start:
 *   npm install @anthropic-ai/sdk
 *   export ANTHROPIC_API_KEY=sk-ant-...
 *   npx tsx ${safeName}.ts
 *
 * Next steps:
 *   1. Implement each tool handler below (search for TODO).
 *   2. Replace the example in main() with your integration logic.
 *   3. Call runAgent() from your application with user messages and history.
 */

import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic();

// ── Agent configuration ────────────────────────────────────────────────────

const AGENT_NAME = ${JSON.stringify(abp.identity.name)};
const MODEL = "claude-opus-4-6";
const MAX_TOKENS = ${maxTokens};

const SYSTEM_PROMPT = \`${escapedSystemPrompt}\`;

// ── Tool definitions ───────────────────────────────────────────────────────

${toolDefsCode}

// ── Tool handlers (implement these) ───────────────────────────────────────

${toolHandlersCode}

// ── Agent runner ───────────────────────────────────────────────────────────

/**
 * Runs the agent with a user message and optional conversation history.
 * Handles multi-turn tool use automatically.
 * Returns the final text response and the updated conversation history.
 */
export async function runAgent(
  userMessage: string,
  history: Anthropic.MessageParam[] = []
): Promise<{ text: string; history: Anthropic.MessageParam[] }> {
  const messages: Anthropic.MessageParam[] = [
    ...history,
    { role: "user", content: userMessage },
  ];

  for (;;) {
    const response = await client.messages.create({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      system: SYSTEM_PROMPT,
      tools: tools.length > 0 ? tools : undefined,
      messages,
    });

    messages.push({ role: "assistant", content: response.content });

    if (response.stop_reason === "end_turn") {
      const text = response.content
        .filter((b): b is Anthropic.TextBlock => b.type === "text")
        .map((b) => b.text)
        .join("\\n");
      return { text, history: messages };
    }

    if (response.stop_reason === "tool_use") {
      const results: Anthropic.ToolResultBlockParam[] = [];
      for (const block of response.content) {
        if (block.type === "tool_use") {
          const handler = toolHandlers[block.name];
          const content = handler
            ? await handler(block.input as Record<string, unknown>)
            : \`Tool "\${block.name}" is not implemented\`;
          results.push({ type: "tool_result", tool_use_id: block.id, content });
        }
      }
      messages.push({ role: "user", content: results });
    }
  }
}

// ── Example ────────────────────────────────────────────────────────────────

async function main() {
  console.log(\`Starting \${AGENT_NAME}...\`);
  const { text } = await runAgent("Hello! What can you help me with?");
  console.log(\`\${AGENT_NAME}: \${text}\`);
}

main().catch(console.error);
`;
}
