/**
 * Multi-Agent Workflow Code Generator — Phase 2
 *
 * Generates a TypeScript orchestration file from a Workflow Definition.
 * Creates a runnable multi-agent pipeline using the Anthropic SDK,
 * with proper handoff logic, shared context, and agent coordination.
 */

import type { WorkflowDefinition, WorkflowAgent, HandoffRule, SharedContextField } from "@/lib/types/workflow";

export interface WorkflowCodeExportMeta {
  workflowId: string;
  workflowName: string;
  version: string;
  exportedAt: string;
}

/**
 * Generates a TypeScript orchestration file from a WorkflowDefinition.
 * Returns the file content as a string.
 */
export function generateWorkflowCode(
  definition: WorkflowDefinition,
  meta: WorkflowCodeExportMeta
): string {
  const { agents, handoffRules, sharedContext } = definition;

  const agentConfigs = agents.map((a) => {
    const safeVar = a.role.replace(/[^a-zA-Z0-9_]/g, "_").replace(/^_+|_+$/g, "");
    return { ...a, varName: safeVar || `agent_${a.agentId.slice(0, 8)}` };
  });

  const sharedContextType = sharedContext.length > 0
    ? sharedContext.map((f) => {
        const tsType = f.type === "json" ? "Record<string, unknown>" : f.type;
        return `  "${f.field}"?: ${tsType}; // ${f.description}`;
      }).join("\n")
    : '  [key: string]: unknown;';

  const handoffFunctions = buildHandoffLogic(handoffRules, agentConfigs);

  return `/**
 * Multi-Agent Orchestration: ${definition.name}
 * ${definition.description}
 *
 * Generated by Intellios — ${meta.exportedAt}
 * Workflow: ${meta.workflowId} v${meta.version}
 *
 * SETUP:
 *   1. npm install @anthropic-ai/sdk
 *   2. Set ANTHROPIC_API_KEY in your environment
 *   3. Implement the TODO sections for each agent's tool handlers
 *   4. Run: npx tsx ${meta.workflowName.replace(/\\s+/g, "-").toLowerCase()}-orchestration.ts
 */

import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic();

// ─── Shared Context ──────────────────────────────────────────────────────────
// Data passed between agents during orchestration.

interface SharedContext {
${sharedContextType}
}

// ─── Agent Definitions ───────────────────────────────────────────────────────

${agentConfigs.map((a) => `const ${a.varName}_CONFIG = {
  agentId: "${a.agentId}",
  role: "${a.role}",
  required: ${a.required},
  model: "claude-sonnet-4-5-20250514" as const,
  systemPrompt: \`You are the "${a.role}" agent in a multi-agent orchestration pipeline.
Your role: ${a.role}.
You receive shared context from previous agents and must update it with your outputs.
Always respond with structured JSON that can be parsed by the orchestrator.\`,
};`).join("\n\n")}

// ─── Agent Runner ────────────────────────────────────────────────────────────

async function runAgent(
  config: { agentId: string; role: string; model: string; systemPrompt: string },
  context: SharedContext,
  input: string
): Promise<{ output: string; updatedContext: SharedContext }> {
  console.log(\`\\n🤖 Running agent: \${config.role} (\${config.agentId.slice(0, 8)})\`);

  const response = await client.messages.create({
    model: config.model,
    max_tokens: 2048,
    system: config.systemPrompt,
    messages: [
      {
        role: "user",
        content: \`## Shared Context\\n\${JSON.stringify(context, null, 2)}\\n\\n## Input\\n\${input}\`,
      },
    ],
  });

  const output = response.content
    .filter((b): b is Anthropic.TextBlock => b.type === "text")
    .map((b) => b.text)
    .join("\\n");

  console.log(\`   ✓ Agent \${config.role} completed (\${response.usage.output_tokens} tokens)\`);

  // Attempt to parse JSON output and merge into context
  let updatedContext = { ...context };
  try {
    const parsed = JSON.parse(output);
    updatedContext = { ...updatedContext, ...parsed };
  } catch {
    // Agent returned free-text — store as last output
    updatedContext = { ...updatedContext, ["lastOutput"]: output } as SharedContext;
  }

  return { output, updatedContext };
}

// ─── Handoff Router ──────────────────────────────────────────────────────────

${handoffFunctions}

// ─── Orchestrator ────────────────────────────────────────────────────────────

async function runOrchestration(initialInput: string): Promise<SharedContext> {
  console.log("═══════════════════════════════════════════════════════════");
  console.log(\`🚀 Starting orchestration: ${definition.name}\`);
  console.log("═══════════════════════════════════════════════════════════");

  let context: SharedContext = {};
  let currentNode = "start";
  let stepCount = 0;
  const MAX_STEPS = 20; // Safety limit to prevent infinite loops

  while (currentNode !== "end" && stepCount < MAX_STEPS) {
    stepCount++;
    const nextNode = getNextNode(currentNode, context);

    if (!nextNode) {
      console.error(\`❌ No matching handoff rule for node: \${currentNode}\`);
      break;
    }

    if (nextNode === "end") {
      console.log("\\n✅ Orchestration complete!");
      break;
    }

    // Find the agent config for this node
    const agentConfig = getAgentConfig(nextNode);
    if (!agentConfig) {
      console.error(\`❌ Unknown agent node: \${nextNode}\`);
      break;
    }

    const input = stepCount === 1 ? initialInput : JSON.stringify(context);
    const result = await runAgent(agentConfig, context, input);
    context = result.updatedContext;
    currentNode = nextNode;
  }

  if (stepCount >= MAX_STEPS) {
    console.warn("⚠️  Reached maximum step limit — orchestration may be in a cycle.");
  }

  console.log("\\n═══════════════════════════════════════════════════════════");
  console.log("📋 Final Context:");
  console.log(JSON.stringify(context, null, 2));
  console.log("═══════════════════════════════════════════════════════════");

  return context;
}

function getAgentConfig(nodeId: string) {
  const configs: Record<string, typeof ${agentConfigs[0]?.varName || "agent"}_CONFIG> = {
${agentConfigs.map((a) => `    "${a.agentId}": ${a.varName}_CONFIG,`).join("\n")}
  };
  return configs[nodeId] ?? null;
}

// ─── Main ────────────────────────────────────────────────────────────────────

const input = process.argv[2] ?? "Hello — please process this request.";
runOrchestration(input)
  .then(() => process.exit(0))
  .catch((err) => {
    console.error("Orchestration failed:", err);
    process.exit(1);
  });
`;
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function buildHandoffLogic(
  rules: HandoffRule[],
  agents: (WorkflowAgent & { varName: string })[]
): string {
  // Group rules by 'from' node
  const rulesByFrom = new Map<string, HandoffRule[]>();
  for (const rule of rules) {
    if (!rulesByFrom.has(rule.from)) rulesByFrom.set(rule.from, []);
    rulesByFrom.get(rule.from)!.push(rule);
  }

  // Sort each group by priority
  for (const [, group] of rulesByFrom) {
    group.sort((a, b) => a.priority - b.priority);
  }

  const cases = [...rulesByFrom.entries()]
    .map(([from, group]) => {
      const conditions = group.map((r) => {
        if (r.condition === "always" || r.condition === "true") {
          return `      // priority ${r.priority}: always → ${r.to}\n      return "${r.to}";`;
        }
        return `      // priority ${r.priority}: ${r.condition}\n      // TODO: Implement condition evaluation\n      // if (evaluateCondition(context, "${r.condition}")) return "${r.to}";`;
      }).join("\n");

      return `    case "${from}":\n${conditions}`;
    })
    .join("\n");

  return `function getNextNode(currentNode: string, context: SharedContext): string | null {
  switch (currentNode) {
${cases}
    default:
      return null;
  }
}`;
}
